version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - '3000'
        environment:
            - NODE_ENV=production
            - NEXT_PUBLIC_CLIENT_DATA=${NEXT_PUBLIC_CLIENT_DATA}
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s
        restart: unless-stopped
